package solver;

public enum F2LComparisonCode {
    SHORTER_F2L,
    SHORTER_LAST_LAYER,
    SHORTER_TOTAL_ROUTE,
    FEWER_ROTATIONS,
    DIFFERENT_PAIR_ORDER,
    LOCAL_PAIR_LONGER_GLOBAL_ROUTE_SHORTER,
    NO_MEASURABLE_IMPROVEMENT
}
