package solver;

public enum F2LReasonCode {
    PAIR_ALREADY_CONNECTED,
    PRESERVES_SOLVED_SLOTS,
    SHORTEST_AVAILABLE_PAIR,
    NO_ROTATION_REQUIRED,
    FEWER_ROTATIONS,
    LOWER_REMAINING_F2L_COST,
    LOWER_TOTAL_CFOP_COST,
    BETTER_GLOBAL_ROUTE,
    RECOVERY_UNPAIR
}
